language: rust
rust:
  - stable
  - beta
  - nightly
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo fmt -- --check
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test --all-targets --all-features
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
