[package]
name = "pea2pea"
version = "0.16.3"
authors = ["ljedrz <ljedrz@gmail.com>"]
edition = "2018"
description = "A small library allowing simple and quick creation of custom P2P nodes and networks."
license = "CC0-1.0"
repository = "https://github.com/ljedrz/pea2pea"
documentation = "https://docs.rs/pea2pea"
readme = "README.md"
categories = ["network-programming", "asynchronous"]
keywords = ["p2p", "peer-to-peer", "networking"]

[lib]
crate-type = ["lib"]

[dependencies]
async-trait = "0.1"
bytes = "1"
fxhash = "0.2"
once_cell = "1"
parking_lot = "0.11"
tokio = { version = "1", features = ["io-util", "macros", "net", "parking_lot", "rt-multi-thread", "sync", "time"] }
tracing = { version = "0.1", features = ["attributes"] }

[dev-dependencies]
bincode = "1"
rand = { version = "0.8", features = ["small_rng"] }
serde = { version = "1", features = ["derive"] }
snow = "0.7"
tracing-subscriber = { version = "0.2", features = ["ansi", "chrono", "env-filter", "fmt", "parking_lot", "smallvec"] }
