[package]
name = "pea2pea"
version = "0.2.0"
authors = ["ljedrz <ljedrz@gmail.com>"]
edition = "2018"
description = "a simple P2P library"
license = "CC0-1.0"
repository = "https://github.com/ljedrz/pea2pea"
readme = "README.md"
categories = ["network-programming", "asynchronous"]
keywords = ["p2p", "peer-to-peer", "networking"]

[lib]
crate-type = ["lib"]

[dependencies]
async-trait = "0.1"
once_cell = "1"
parking_lot = "0.11"
tokio = { version = "0.3", features = ["io-util", "macros", "net", "parking_lot", "rt-multi-thread", "sync", "time"] }
tracing = { version = "0.1", features = ["attributes"] }

[dev-dependencies]
snow = "0.7"
tracing-subscriber = { version = "0.2", features = ["ansi", "chrono", "env-filter", "fmt", "parking_lot", "smallvec"] }
